FROM node:12.18.4-alpine3.11 

WORKDIR /app
COPY . .
#COPY package.json package.json

RUN npm install && npm run build


# COPY .babelrc .env karma.conf.js tests.webpack.js webpack.config.js ./

# VOLUME /app/src

CMD ["npm", "run", "start"]